### ISSUE TITLE
Catch up on all new features up to v2.5.0 of DLL

### ISSUE THREAD

**Issue by LeeDongGeon1996** [facioquo/stock-indicators-python#338]
## v1.2.0
- [x] #341 - https://github.com/DaveSkender/Stock.Indicators/pull/948 (v2.4.1)
- [x] https://github.com/DaveSkender/Stock.Indicators.Python/pull/342(https://github.com/DaveSkender/Stock.Indicators.Python/pull/342) - https://github.com/DaveSkender/Stock.Indicators/pull/1081 (v2.4.11)
- [x] #343 - (https://github.com/DaveSkender/Stock.Indicators/pull/1046) (v2.4.11)
- [x] #344 - see https://github.com/DaveSkender/Stock.Indicators/pull/845 for explanation (v2.1.0)
- [x] #337 
    - [x] HtTrendline, SMI, StarcBand, TrueRange
    - [x] Add all nicknames of indicators
    - [x] [18a02f5](https://github.com/DaveSkender/Stock.Indicators.Python/pull/337/commits/18a02f541fb74dfbc3757a24968ff882bffabf03) - https://github.com/DaveSkender/Stock.Indicators/pull/978 (v2.4.7)
    - [x] [511567a](https://github.com/DaveSkender/Stock.Indicators.Python/pull/337/commits/511567a3f011f42d23e4cd9509e608a16bbf1f63) - https://github.com/DaveSkender/Stock.Indicators/pull/1030 (v2.4.10)

## v1.3.0
- [x] https://github.com/DaveSkender/Stock.Indicators.Python/pull/367 - https://github.com/DaveSkender/Stock.Indicators/pull/875 (v2.2.0)
   - [x] add configurable adjustment k-factor for [McGinley Dynamic](https://daveskender.github.io/Stock.Indicators/indicators/Dynamic/#content) - https://github.com/DaveSkender/Stock.Indicators/pull/901 (v2.4.0)
- [x] https://github.com/DaveSkender/Stock.Indicators.Python/pull/369 - https://github.com/DaveSkender/Stock.Indicators/pull/891 (v2.3.0)
- [x] https://github.com/DaveSkender/Stock.Indicators.Python/pull/370 - https://github.com/DaveSkender/Stock.Indicators/pull/893 (v2.3.0)
- [x] https://github.com/DaveSkender/Stock.Indicators.Python/pull/372
- [x] https://github.com/facioquo/stock-indicators-python/pull/377
- [x] https://github.com/facioquo/stock-indicators-python/pull/378
- [x] https://github.com/facioquo/stock-indicators-python/pull/379

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Ready to deploy v1.2.0 :) Do you have any lefts for this version?

**Comment by DaveSkender** [comment]
> @DaveSkender Ready to deploy v1.2.0 :) Do you have any lefts for this version?

I don't, but was just looking at the environment variables and don't see any of the tokens defined for either the test or production PyPI deployer, not do I see references to them in `deploy.yml`.  How did this even work last time we published without them?

 ... nevermind.  I just remembered they have a weird _Trusted Publisher Management_ feature where you register on their site.  Unusual.

**Comment by LeeDongGeon1996** [comment]
@DaveSkender I'd like to release it now as the version 1.2.1. How do you think?

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Please approve v1.2.1 when you are available 🚀

**Comment by LeeDongGeon1996** [comment]
@DaveSkender 
I'm thinking about not to support `condense()` for now. It might be more efficient for users to "condense" on their side.
