### ISSUE TITLE
Renko ATR docs: "does not return the same number" typographical error

### ISSUE THREAD

**Issue by carusyte** [facioquo/stock-indicators-python#405]
### What happened?

The result of `indicators.get_renko_atr(quotes_list, atr_periods=N)` returns less elements than `len(quote_list)`, which contradicts the document that reads "It always returns the same number of elements as there are in the historical quotes."

https://python.stockindicators.dev/indicators/Renko/#content:~:text=It%20always%20returns%20the%20same%20number%20of%20elements%20as%20there%20are%20in%20the%20historical%20quotes.

**Comment by DaveSkender** [comment]
❤️ thank you for reporting.  This is an error in our documentation and should have the same warning as you see further up the page for _normal_ Renko.

**Comment by DaveSkender** [comment]
Fix has been deployed to docs site, thanks again.

**Comment by DaveSkender** [comment]
Oops, think I missed a spot.

**Comment by DaveSkender** [comment]
Hehe, nevermind.  I did it right, but please do let me know if it's still too confusing or looks to be incorrect to you.
